config/routes.rb
Rails.application.routes.draw do

  root to: "books#index"

  # The syntax for generating the seven conventional RESTful routes for a given controller are:
  # resources _a symbol of the name of the controller_
  resources :books
  resources :authors do
    # This is equivelant to only: [:index, :new, :create]
    resources :books, shallow: true
  end

  # get "/login", to: "users#login_form", as: "login"
  # post "/login", to: "users#login"
  # post "/logout", to: "users#logout", as: "logout"
  get "/users/current", to: "users#current", as: "current_user"

  get "/auth/github", as: "github_login"
  get "/auth/github/callback", to: "users#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def first_published
    books_with_year = self.books.where.not(publication_date: nil)
    first_book = books_with_year.order(publication_date: :asc).first
    return first_book.publication_date
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  validates :title, presence: true

  def self.all_in_alpha_order
    return Book.all.order(title: :asc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.build_from_github(auth_hash)
    user = User.new
    user.uid = auth_hash[:uid]
    user.provider = "github"
    user.name = auth_hash["info"]["name"]
    user.email = auth_hash["info"]["email"]

    # Note that the user has not been saved.
    # We'll choose to do the saving outside of this method
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
      @authors = Author.all
  end

  def show
    author_id = params[:id].to_i
    @author = Author.find_by(id: author_id)
    if @author.nil?
      head :not_found
      return
    end
  end

  def new
      @author = Author.new
  end

  def create
    @author = Author.new( author_params )
    if @author.save
      redirect_to author_path(@author.id)
    else
      render new_author_path
    end
  end

  def edit
    @author = Author.find_by(id: params[:id] )
  end

  def update
    @author = Author.find_by(id: params[:id] )
    if @author.update( author_params )
      redirect_to author_path(@author.id)
    else
      render new_author_path
    end
  end

  def destroy

    the_correct_author = Author.find_by( id: params[:id] )

    if the_correct_author.nil?
      redirect_to authors_path
      return
    else
      the_correct_author.destroy
      redirect_to root_path
      return
    end
  end

  private             

  def author_params
    return params.require(:author).permit(:name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book, only: [:show, :edit, :update]

  # Can now be accessed via /, /books, or /authors/:author_id/books
  def index
    author_id = params[:author_id]
    # If not coming from /authors/:author_id/books
    if author_id.nil?
      @books = Book.all
    else
      @author = Author.find_by(id: author_id)
      if @author
        @books = @author.books
      # We couldn't find the given author_id in the database
      else
        head :not_found
      end
    end
  end

  def show
    if @book.nil?
      head :not_found
      return
    end
  end

  def new
    author_id = params[:author_id]
    @book = Book.new
    @authors = Author.all
    if author_id
      @authors = [Author.find_by(id: author_id)]
    end
  end

  def create
    @book = Book.new( book_params )
    @authors = Author.all

    if @book.save
      # If the book saves correctly, we will notify the user that it was good using flash, and then redirect them to the book show page
      flash[:success] = "Book #{@book.id} added successfully"
      redirect_to book_path(@book.id)
    else
      flash.now[:error] = "You didn't do it right."
      render new_book_path
    end
  end

  def edit
    @authors = Author.all
  end

  def update
    # Instead of doing @book.title = ... assignment, and then @book.save, we will instead do "if @book.update( book_params )" to use strong params pattern. @book.update() will be false if the update was unsuccessful
    if @book.update( book_params )
      redirect_to book_path(@book.id)
    else
      render new_book_path
    end
  end

  def destroy
    # We will find the right book using the id found in params
    # Then, depending on if we find it...
    #   we will either destroy it, then we will redirect to root page
    #   or not! and we will redirect to index page

    the_correct_book = Book.find_by( id: params[:id] )

    # Because find_by will give back nil if the book is not found...

    if the_correct_book.nil?
      # Then the book was not found!
      redirect_to books_path
      return
    else
      # Then we did find it!
      the_correct_book.destroy
      flash[:success] = "Your book " + the_correct_book.title + " was successfully deleted!"
      redirect_to root_path
      return
    end
  end

  private

  def find_book
    @book = Book.find_by(id: params[:id])
  end

  # Every method defined under the word private is going to be a private method

  def book_params
    # The responsibility of this method is to return "strong params"
    # .require is used when we use form_with and a model, and therefore our expected form data has the "book" hash inside of it
    # .permit takes in a list of names of attributes to allow... (aka the new Book form has title, author, description)
    return params.require(:book).permit(:title, :author_id, :description)

    # Remember: If you ever update the database, model, and form, this will also need to be updated
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    auth_hash = request.env["omniauth.auth"]
    user = User.find_by(uid: auth_hash[:uid], provider: "github")
    if user
      # user was found in db
      # log theem in to session
      flash[:success] = "Logged in as returning user #{user.name}"
    else
      # user not in DB, try to create new user
      # user = User.new(uid: auth_hash[:uid], provider: "github", name: auth_hash[:info][:name], email: auth_hash[:info][:email] )
      user = User.build_from_github(auth_hash)
      if user.save
        flash[:success] = "Logged in as new user #{user.name}"
      else
        flash[:error] = "something went wrong,sry"
      end
    end
    session[:user_id] = user.id
    redirect_to root_path

  end

  def login_form
    @user = User.new
  end

  def login
    username = params[:user][:username]

    found_user = User.find_by(username: username)

    if found_user
      # We DID find a user!
      session[:user_id] = found_user.id
      flash[:message] = "Logged in as returning user!"
    else
      # We did not find an existing user. Let's try to make one!
      new_user = User.new(username: username)
      new_user.save
      # TODO: What happens if saving fails?
      session[:user_id] = new_user.id
      flash[:message] = "Created a new user. Welcome!"
    end

    return redirect_to root_path
  end

  def logout
    # TODO: What happens if we were never logged in?
    session[:user_id] = nil
    flash[:message] = "You have logged out successfully."
    return redirect_to root_path
  end

  def current
    @user = User.find_by(id: session[:user_id])
    if @user.nil?
      head :not_found
      return
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_date(date)
    return "[unknown]" unless date
    return (
      "<span class='date' title='".html_safe +
      date.to_s +
      "'>".html_safe +
      time_ago_in_words(date) +
      " ago</span>".html_safe
    )
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<h1 class="index-header">The Index Action: The place where you get all of the authors!</h1>

<section>
  <h2>List of all Authors</h2>
  <ul>
    <% @authors.each do |author| %>
      <li>
        <%= link_to author.name, author_path( author.id ) %>
        <%= link_to "(Delete)", author_path( author.id ), method: :delete, data: { confirm: "Are YOU sure?" }, class: "index-delete-link" %>
      </li>
    <% end %>
  </ul>
</section>

app/views/authors/show.html.erb
<header class="show-header">
  <h1><%=@author.name%></h1>
  <%= link_to "Edit this author!", edit_author_path(@author.id) %>
</header>

<section class="show-details">

  <p>I don't know anything about this author but here's Ada Lovelace!</p>

  <%= image_tag "https://smsa.org.au/assets/ada-with-diagram.jpg", alt: "Ada being a badass", class: "show-ada" %>

</section>

app/views/books/_form.html.erb
<%# form_with is a view helper that will generate the proper form for us and will help us hook into the other controller actions %>
<%= form_with model: @book, class: book_form_class do |f| %>

  <%# f.text_field :somenameofsomeattributeonbook ... in this case, :title %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%  %>
  <%= f.select :author_id, @authors.map{ |auth| [auth.name, auth.id] } %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  
  <%= f.submit submit_button_label, class: "book-form-button" %>

<% end %>

app/views/books/edit.html.erb
<h2>Edit Book Form</h2>

<%= render partial: "form", locals: { submit_button_label: "Edit Book", book_form_class: "edit-book-form" } %>

app/views/books/index.html.erb
<h1 class="index-header">The Index Action: The place where you get all of the books!</h1>

<section>
  <h2>
    List of all Books 
    <% if @author %>
      by <%= @author.name %>
    <% end %>
  </h2>
  <ul>
    <% @books.each do |book| %>
      <li>
        <%= link_to book.title, book_path( book.id ) %> by <%= book.author.name %>
        <%= link_to "(Delete)", book_path( book.id ), method: :delete, data: { confirm: "Are YOU sure?" }, class: "index-delete-link" %>
      </li>
    <% end %>
  </ul>
  <% if @author %>
    <%= link_to "Create a new book by " + @author.name, new_author_book_path %>
  <% end %>
</section>

app/views/books/new.html.erb
<h2>New Book Form</h2>

<% if @book.errors.any? %>
  <ul class="errors">
    <% @book.errors.each do |column, message| %>
      <li>
        <strong><%= column.capitalize %></strong> <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

<%# This is how we render a partial with the name _form.html.erb ! %>
<%# Sometimes we want to pass a local variable to the partial. That's the locals part! %>
<%# For every local variable that we want to define for our partial, we put it in locals (Just as a reminder, locals is a hash) %>
<%= render partial: "form", locals: { submit_button_label: "Create Book", book_form_class: "new-book-form" } %>

app/views/books/show.html.erb
<header class="show-header">
  <h1><%=@book.title%></h1>
  <h2>by <%=@book.author.name%></h2>
  <%= link_to "Edit this book!", edit_book_path(@book.id) %>
</header>

<section class="show-details">

  <p>
    About this book: <%= @book.description %>
  </p>

  <p>
    This book was published <%= readable_date(@book.publication_date) %>
  </p>

  <%= image_tag "https://www.top13.net/wp-content/uploads/2016/10/most-beautiful-cats-world-11.jpg", alt: "The most beautiful cat in the world (A cat with long and dark fur staring into the camera directly", class: "show-cat" %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C12 Branches Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <ul>
        <li>
          <%# This is the syntax for defining a link in HTML (More in depth in View Helpers lesson) %>
          <%= link_to "Home!", root_path %>
        </li>
        <li>
          <%= link_to "Go to the Books Index Page", books_path %>
        </li>
                <li>
          <%= link_to "Go to the Authors Index Page", authors_path %>
        </li>
        <li>
          <%= link_to "Let's make a NEW book", new_book_path %>
        </li>
        <li>
          <%= link_to "Log In with Github", github_login_path %>
        </li>
        <li>
          <%= link_to "Current User", current_user_path %>
        </li>
        <li>
          <%# link_to "Log Out!", logout_path, method: :post %>
        </li>
      </ul>
    </nav>

    <%# Our nice generic way of displaying flash messages: Iterating over the hash-like structure of flash and setting all HTML elements and CSS classes however we want. %>
    <section class="user-messages">
      <% flash.each do |name, message| %>
        <div class="<%= name %>"><%= name.capitalize %>: <%= message %></div>
      <% end %>
    </section>


    <%= yield %>
  </body>
</html>

app/views/users/current.html.erb
<h1>About the Current User...</h1>

<% if @user.nil? %>
  <p>I am not logged in!</p>
<% else %>
  <p>I'm logged in! My name is: <%= @user.name %></p>
  <p>I'm logged in! My UID is: <%= @user.uid %></p>
<% end %>

app/views/users/login_form.html.erb
<h1>Login Form :)</h1>

<%= form_with model: @user, url: login_path do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.submit "Log in" %>

<% end %>